# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateMoment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, time: str=None, comments: List[str]=None, contents: str=None):  # noqa: E501
        """CreateMoment - a model defined in Swagger

        :param user_id: The user_id of this CreateMoment.  # noqa: E501
        :type user_id: str
        :param time: The time of this CreateMoment.  # noqa: E501
        :type time: str
        :param comments: The comments of this CreateMoment.  # noqa: E501
        :type comments: List[str]
        :param contents: The contents of this CreateMoment.  # noqa: E501
        :type contents: str
        """
        self.swagger_types = {
            'user_id': str,
            'time': str,
            'comments': List[str],
            'contents': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'time': 'time',
            'comments': 'comments',
            'contents': 'contents'
        }

        self._user_id = user_id
        self._time = time
        self._comments = comments
        self._contents = contents

    @classmethod
    def from_dict(cls, dikt) -> 'CreateMoment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createMoment of this CreateMoment.  # noqa: E501
        :rtype: CreateMoment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this CreateMoment.


        :return: The user_id of this CreateMoment.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this CreateMoment.


        :param user_id: The user_id of this CreateMoment.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def time(self) -> str:
        """Gets the time of this CreateMoment.


        :return: The time of this CreateMoment.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this CreateMoment.


        :param time: The time of this CreateMoment.
        :type time: str
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def comments(self) -> List[str]:
        """Gets the comments of this CreateMoment.


        :return: The comments of this CreateMoment.
        :rtype: List[str]
        """
        return self._comments

    @comments.setter
    def comments(self, comments: List[str]):
        """Sets the comments of this CreateMoment.


        :param comments: The comments of this CreateMoment.
        :type comments: List[str]
        """
        if comments is None:
            raise ValueError("Invalid value for `comments`, must not be `None`")  # noqa: E501

        self._comments = comments

    @property
    def contents(self) -> str:
        """Gets the contents of this CreateMoment.


        :return: The contents of this CreateMoment.
        :rtype: str
        """
        return self._contents

    @contents.setter
    def contents(self, contents: str):
        """Sets the contents of this CreateMoment.


        :param contents: The contents of this CreateMoment.
        :type contents: str
        """
        if contents is None:
            raise ValueError("Invalid value for `contents`, must not be `None`")  # noqa: E501

        self._contents = contents
