# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Query(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, query_key: List[List[str]]=None):  # noqa: E501
        """Query - a model defined in Swagger

        :param query_key: The query_key of this Query.  # noqa: E501
        :type query_key: List[List[str]]
        """
        self.swagger_types = {
            'query_key': List[List[str]]
        }

        self.attribute_map = {
            'query_key': 'query_key'
        }

        self._query_key = query_key

    @classmethod
    def from_dict(cls, dikt) -> 'Query':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The query of this Query.  # noqa: E501
        :rtype: Query
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query_key(self) -> List[List[str]]:
        """Gets the query_key of this Query.


        :return: The query_key of this Query.
        :rtype: List[List[str]]
        """
        return self._query_key

    @query_key.setter
    def query_key(self, query_key: List[List[str]]):
        """Sets the query_key of this Query.


        :param query_key: The query_key of this Query.
        :type query_key: List[List[str]]
        """
        if query_key is None:
            raise ValueError("Invalid value for `query_key`, must not be `None`")  # noqa: E501

        self._query_key = query_key
