# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateOnline(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, status: str=None):  # noqa: E501
        """UpdateOnline - a model defined in Swagger

        :param id: The id of this UpdateOnline.  # noqa: E501
        :type id: str
        :param status: The status of this UpdateOnline.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': str,
            'status': str
        }

        self.attribute_map = {
            'id': '_id',
            'status': 'status'
        }

        self._id = id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateOnline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The updateOnline of this UpdateOnline.  # noqa: E501
        :rtype: UpdateOnline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this UpdateOnline.


        :return: The id of this UpdateOnline.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UpdateOnline.


        :param id: The id of this UpdateOnline.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this UpdateOnline.


        :return: The status of this UpdateOnline.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this UpdateOnline.


        :param status: The status of this UpdateOnline.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
