# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateAccount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_name: str=None, pwd: str=None):  # noqa: E501
        """CreateAccount - a model defined in Swagger

        :param user_name: The user_name of this CreateAccount.  # noqa: E501
        :type user_name: str
        :param pwd: The pwd of this CreateAccount.  # noqa: E501
        :type pwd: str
        """
        self.swagger_types = {
            'user_name': str,
            'pwd': str
        }

        self.attribute_map = {
            'user_name': 'user_name',
            'pwd': 'pwd'
        }

        self._user_name = user_name
        self._pwd = pwd

    @classmethod
    def from_dict(cls, dikt) -> 'CreateAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createAccount of this CreateAccount.  # noqa: E501
        :rtype: CreateAccount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_name(self) -> str:
        """Gets the user_name of this CreateAccount.


        :return: The user_name of this CreateAccount.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this CreateAccount.


        :param user_name: The user_name of this CreateAccount.
        :type user_name: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    @property
    def pwd(self) -> str:
        """Gets the pwd of this CreateAccount.


        :return: The pwd of this CreateAccount.
        :rtype: str
        """
        return self._pwd

    @pwd.setter
    def pwd(self, pwd: str):
        """Sets the pwd of this CreateAccount.


        :param pwd: The pwd of this CreateAccount.
        :type pwd: str
        """
        if pwd is None:
            raise ValueError("Invalid value for `pwd`, must not be `None`")  # noqa: E501

        self._pwd = pwd
