# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetOnline(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: List[str]=None):  # noqa: E501
        """GetOnline - a model defined in Swagger

        :param id: The id of this GetOnline.  # noqa: E501
        :type id: List[str]
        """
        self.swagger_types = {
            'id': List[str]
        }

        self.attribute_map = {
            'id': '_id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'GetOnline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getOnline of this GetOnline.  # noqa: E501
        :rtype: GetOnline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> List[str]:
        """Gets the id of this GetOnline.


        :return: The id of this GetOnline.
        :rtype: List[str]
        """
        return self._id

    @id.setter
    def id(self, id: List[str]):
        """Sets the id of this GetOnline.


        :param id: The id of this GetOnline.
        :type id: List[str]
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
